###
GET http://localhost:4000/api/customers

###
POST http://localhost:4000/api/customers
Content-Type: application/json

{
    "name": "Jose",
    "lastName": "Lopez",
    "phoneNumber" : 15111234554,
    "email": "jose@gmail.com",
    "inquiry": "reclamo"
}

###
GET http://localhost:4000/api/customers/62c6ffc6d61584b72626b234

###
PUT http://localhost:4000/api/customers/62c6ffc6d61584b72626b234
Content-Type: application/json

{

    "phoneNumber": 151234567
    
}

###
DELETE http://localhost:4000/api/customers/62c03a82ad866bf1a340d84f
